### ISSUE TITLE
Add a URL

### ISSUE THREAD

**Issue by webknjaz** [hmara-info/language-settings-manager#1]
It's hard to navigate to the website w/o having to copy&edit the org name.

I suggest you to edit the repo and org descriptions, and fill out the URL fields. Bonus: you can also mark the domain as verified, this would require adding a TXT entry to the DNS zone.

P.S. You may also want to enter the Twitter account name in the org settings.

**Comment by yko** [comment]
Sooooo muuuuuuch wooooooooork..... 😿

**Comment by yko** [comment]
Okaaaay, okaaaaay, doing sooooo muuuuuuch wooooooooork here..... 😿
