### ISSUE TITLE
Automate releases to FIrefox / addons.mozilla.org

### ISSUE THREAD

**Issue by yko** [hmara-info/language-settings-manager#19]
Releasing manually is annoying and prone to errors.
There was a (failed) attempt ba1f2370d9fc2d6b.

I'm not sure what happened there, but it was not working, and I didn't have time to dig deeper 😅
One piece of context is that in addition to .xpi, mozilla requires to submit source code and build instruction.

Source code: `git archive --format=tar.gz main > language-settings-manager.tar.gz`
Build command `FIREFOX=1 npm run prod && cd build && zip -r ../language-settings-manager.xpi * && cd ..`

**Comment by UnforbiddenYet** [comment]
We should be using the https://github.com/mozilla/web-ext for such purposes. It provides a way to sign the extension and upload it for review. For automation, we coll look into GitHub actions and link it to master merge or something.

Also, the tool is helpful for development as well and it works in Chrome. So we could potentially minimize the surface area of the dev scripts for FF/Chrome. As for Safari, it doesn't help us here, so we still need the custom process.

**Comment by yko** [comment]
> For automation, we could look into GitHub actions and trigger the process via the merge to master.

That's already in place for Chrome. See https://github.com/hmara-info/language-settings-manager/blob/ba1f2370d9fc2d6b83b4987e6f63e2362263996f/.github/workflows/prod.yml

**Comment by yko** [comment]
Closed by 2e2a394
